FROM swaggerapi/swagger-ui:latest

COPY index.html /usr/share/nginx/html/docs/index.html
COPY account-swagger.yaml /usr/share/nginx/html/docs/account-swagger.yaml
COPY document-swagger.yaml /usr/share/nginx/html/docs/document-swagger.yaml
COPY hospital-swagger.yaml /usr/share/nginx/html/docs/hospital-swagger.yaml
COPY timetable-swagger.yaml /usr/share/nginx/html/docs/timetable-swagger.yaml
